
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#使用多个eureka实例，模拟创建集群环境.两台机器相互注册
server:
  port: 8761
spring:
  profiles: slaveB
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://slave1:8762/eureka
---
server:
  port: 8762
spring:
  profiles: slaveA
eureka:
  client:
    serviceUrl: 
      defaultZone: http://slave2:8761/eureka

  

